# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# spatiotemporal SPDE distribution ----
## Setup ----

# Helper: build small hard-coded SPDE inputs for a 3-node mesh, 2 years.
# C0 = diagonal mass matrix
# C1 = diagonal mixed stiffness matrix
# C2 = tridiagonal stiffness (path-graph Laplacian + identity to ensure PD)
# A  = identity (each observation at one node)
make_spde_inputs <- function() {
  n_nodes <- 3L
  n_years <- 2L

  # C0: diagonal with value 0.1 (mass matrix)
  C0 <- list(i = c(0, 1, 2), j = c(0, 1, 2), v = c(0.1, 0.1, 0.1))

  # C1: diagonal with value 0.5 (mixed stiffness)
  C1 <- list(i = c(0, 1, 2), j = c(0, 1, 2), v = c(0.5, 0.5, 0.5))

  # C2: tridiagonal Laplacian (path graph) + identity for positive definiteness
  # [[2.5, -0.5, 0], [-0.5, 3.0, -0.5], [0, -0.5, 2.5]]
  C2 <- list(
    i = c(0, 0, 1, 1, 1, 2, 2),
    j = c(0, 1, 0, 1, 2, 1, 2),
    v = c(2.5, -0.5, -0.5, 3.0, -0.5, -0.5, 2.5)
  )

  # A: identity (3 obs per year, each at exactly one node), total 6 obs
  A <- list(
    i = c(0, 1, 2, 3, 4, 5),  # observation index (0-based)
    j = c(0, 1, 2, 0, 1, 2),  # node index (0-based)
    v = c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
  )

  y_obs       <- c(1.5, 2.0, 1.8, 1.3, 1.7, 2.1)
  obs_year_idx <- c(0, 0, 0, 1, 1, 1)  # 0-based year index

  list(
    n_nodes      = n_nodes,
    n_years      = n_years,
    C0           = C0,
    C1           = C1,
    C2           = C2,
    A            = A,
    y_obs        = y_obs,
    obs_year_idx = obs_year_idx
  )
}

## IO correctness ----
test_that("SpatiotemporalSPDE object can be constructed from R", {
  clear()
  inp <- make_spde_inputs()

  #' @description Test that SpatiotemporalSPDE Rcpp object can be created without error.
  expect_no_error({
    spde <- methods::new(SpatiotemporalSPDE)
  })

  #' @description Test that SpatiotemporalSPDE get_id() returns a positive integer.
  expect_true(spde$get_id() > 0L)

  clear()
})

test_that("SpatiotemporalSPDE fields can be set from R", {
  clear()
  inp <- make_spde_inputs()

  spde <- methods::new(SpatiotemporalSPDE)
  spde$n_nodes <- inp$n_nodes
  spde$n_years <- inp$n_years

  spde$C0_i <- inp$C0$i
  spde$C0_j <- inp$C0$j
  spde$C0_v <- inp$C0$v

  #' @description Test that n_nodes field is set correctly.
  expect_equal(spde$n_nodes, inp$n_nodes)
  #' @description Test that C0_v field is set correctly.
  expect_equal(as.numeric(spde$C0_v), inp$C0$v)

  clear()
})

test_that("SpatiotemporalSPDE evaluate() returns a finite value", {
  clear()
  inp <- make_spde_inputs()

  spde <- methods::new(SpatiotemporalSPDE)
  spde$n_nodes <- inp$n_nodes
  spde$n_years <- inp$n_years

  spde$C0_i <- inp$C0$i; spde$C0_j <- inp$C0$j; spde$C0_v <- inp$C0$v
  spde$C1_i <- inp$C1$i; spde$C1_j <- inp$C1$j; spde$C1_v <- inp$C1$v
  spde$C2_i <- inp$C2$i; spde$C2_j <- inp$C2$j; spde$C2_v <- inp$C2$v
  spde$A_i  <- inp$A$i;  spde$A_j  <- inp$A$j;  spde$A_v  <- inp$A$v

  spde$y_obs        <- inp$y_obs
  spde$obs_year_idx <- inp$obs_year_idx

  # Set initial parameter values
  spde$beta0[1]$value         <- 0.5
  spde$rho_logit[1]$value     <- 0.0
  spde$log_kappa[1]$value     <- 0.0
  spde$log_tau[1]$value       <- 0.0
  spde$log_sigma_obs[1]$value <- log(0.3)

  # Set omega initial values
  n_omega <- inp$n_nodes * inp$n_years
  spde$omega$resize(n_omega)
  for (k in seq_len(n_omega)) {
    spde$omega[k]$value <- 0.0
  }

  # evaluate() without TMB returns 0 (TMB_MODEL not defined outside TMB context)
  # but should not error
  #' @description Test that SpatiotemporalSPDE evaluate() runs without error.
  expect_no_error(val <- spde$evaluate())
  #' @description Test that SpatiotemporalSPDE evaluate() returns a numeric value.
  expect_true(is.numeric(val))

  clear()
})

test_that("SpatiotemporalSPDE end-to-end: CreateTMBModel produces finite NLL", {
  skip_if_not_installed("TMB")
  clear()

  inp <- make_spde_inputs()

  spde <- methods::new(SpatiotemporalSPDE)
  spde$n_nodes <- inp$n_nodes
  spde$n_years <- inp$n_years

  spde$C0_i <- inp$C0$i; spde$C0_j <- inp$C0$j; spde$C0_v <- inp$C0$v
  spde$C1_i <- inp$C1$i; spde$C1_j <- inp$C1$j; spde$C1_v <- inp$C1$v
  spde$C2_i <- inp$C2$i; spde$C2_j <- inp$C2$j; spde$C2_v <- inp$C2$v
  spde$A_i  <- inp$A$i;  spde$A_j  <- inp$A$j;  spde$A_v  <- inp$A$v

  spde$y_obs        <- inp$y_obs
  spde$obs_year_idx <- inp$obs_year_idx

  # Fixed effects
  spde$beta0[1]$value              <- 0.5
  spde$beta0[1]$estimation_type    <- "fixed_effects"
  spde$rho_logit[1]$value          <- 0.0
  spde$rho_logit[1]$estimation_type <- "fixed_effects"
  spde$log_kappa[1]$value          <- 0.0
  spde$log_kappa[1]$estimation_type <- "constant"
  spde$log_tau[1]$value            <- 0.0
  spde$log_tau[1]$estimation_type  <- "constant"
  spde$log_sigma_obs[1]$value      <- log(0.3)
  spde$log_sigma_obs[1]$estimation_type <- "fixed_effects"

  # Random effects: omega
  n_omega <- inp$n_nodes * inp$n_years
  spde$omega$resize(n_omega)
  for (k in seq_len(n_omega)) {
    spde$omega[k]$value           <- 0.0
    spde$omega[k]$estimation_type <- "random_effects"
  }

  #' @description Test that CreateTMBModel() succeeds with a SpatiotemporalSPDE distribution.
  expect_no_error(CreateTMBModel())

  # Get initial parameter vectors
  p  <- get_fixed()
  re <- get_random()

  #' @description Test that at least one fixed-effect parameter is registered (beta0, rho_logit, log_sigma_obs).
  expect_true(length(p) >= 1L)

  #' @description Test that random-effect vector has n_nodes * n_years elements.
  expect_equal(length(re), n_omega)

  # Build TMB objective function
  obj <- TMB::MakeADFun(
    data       = list(),
    parameters = list(p = p, re = re),
    random     = "re",
    DLL        = "FIMS",
    silent     = TRUE
  )

  # Evaluate NLL at initial values
  nll <- obj$fn(obj$par)

  #' @description Test that the NLL from the spatiotemporal SPDE model is finite at initial parameter values.
  expect_true(is.finite(nll))

  clear()
})

## Edge handling ----
test_that("SpatiotemporalSPDE handles zero omega correctly", {
  clear()
  inp <- make_spde_inputs()

  spde <- methods::new(SpatiotemporalSPDE)
  spde$n_nodes <- inp$n_nodes
  spde$n_years <- inp$n_years
  spde$C0_i <- inp$C0$i; spde$C0_j <- inp$C0$j; spde$C0_v <- inp$C0$v
  spde$C1_i <- inp$C1$i; spde$C1_j <- inp$C1$j; spde$C1_v <- inp$C1$v
  spde$C2_i <- inp$C2$i; spde$C2_j <- inp$C2$j; spde$C2_v <- inp$C2$v
  spde$A_i  <- inp$A$i;  spde$A_j  <- inp$A$j;  spde$A_v  <- inp$A$v
  spde$y_obs        <- inp$y_obs
  spde$obs_year_idx <- inp$obs_year_idx
  spde$beta0[1]$value <- 0.5
  spde$log_sigma_obs[1]$value <- log(0.3)
  n_omega <- inp$n_nodes * inp$n_years
  spde$omega$resize(n_omega)
  # All omega = 0 (zero field)
  for (k in seq_len(n_omega)) spde$omega[k]$value <- 0.0

  #' @description Test that SpatiotemporalSPDE evaluate() does not error when omega is all zeros.
  expect_no_error(spde$evaluate())

  clear()
})

## Error handling ----
test_that("SpatiotemporalSPDE returns error when given incorrect input", {
  #' @description Test that SpatiotemporalSPDE constructor errors with wrong argument type.
  expect_error(
    methods::new(SpatiotemporalSPDE, "bad_arg"),
    regexp = "no valid constructor"
  )
})
