# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().

reset_julia_backend_state <- function() {
  original_state <- FIMS:::.fims_julia_backend_state$initialized
  withr::defer(
    FIMS:::.fims_julia_backend_state$initialized <- original_state,
    envir = parent.frame()
  )
  FIMS:::.fims_julia_backend_state$initialized <- FALSE
}

test_that("reset_julia_backend_state restores the Julia initialization flag", {
  FIMS:::.fims_julia_backend_state$initialized <- TRUE
  local({
    reset_julia_backend_state()
    expect_false(FIMS:::.fims_julia_backend_state$initialized)
  })
  expect_true(FIMS:::.fims_julia_backend_state$initialized)
})

test_that("Julia backend package scaffolding exists", {
  backend_root <- normalizePath(
    FIMS:::julia_backend_package_path(),
    "/",
    mustWork = TRUE
  )

  #' @description Test that the Julia backend Project.toml exists.
  expect_true(file.exists(file.path(backend_root, "Project.toml")))
  #' @description Test that the Julia backend top-level module exists.
  expect_true(file.exists(file.path(backend_root, "src", "FIMSBackend.jl")))
  #' @description Test that the Julia backend selectivity module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "selectivity.jl")))
  #' @description Test that the Julia backend recruitment module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "recruitment.jl")))
  #' @description Test that the Julia backend population module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "population.jl")))
})

test_that("Julia backend helpers return package paths", {
  backend_path <- FIMS:::julia_backend_package_path()
  module_path <- FIMS:::julia_backend_module_path()
  installed_root <- system.file(package = "FIMS")

  #' @description Test that the Julia backend package path is a character scalar.
  expect_type(backend_path, "character")
  #' @description Test that the Julia backend module path is a character scalar.
  expect_type(module_path, "character")
  #' @description Test that the explicit libname/pkgname lookup resolves the same Julia backend path.
  expect_equal(
    normalizePath(
      FIMS:::julia_backend_package_path(libname = dirname(installed_root), pkgname = "FIMS"),
      "/",
      mustWork = TRUE
    ),
    backend_path
  )
  #' @description Test that the explicit libname/pkgname lookup resolves the same Julia backend module path.
  expect_equal(
    normalizePath(
      FIMS:::julia_backend_module_path(libname = dirname(installed_root), pkgname = "FIMS"),
      "/",
      mustWork = TRUE
    ),
    module_path
  )
})

test_that("initialize_fims validates backend selection", {
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)

  #' @description Test that initialize_fims keeps the default TMB backend when no backend is specified.
  expect_null(attr(FIMS::initialize_fims(parameters = parameters, data = data), "backend"))
  #' @description Test that initialize_fims rejects unsupported backend values.
  expect_error(
    FIMS::initialize_fims(parameters = parameters, data = data, backend = "bogus"),
    regexp = "arg"
  )

  clear()
})

test_that("Julia backend input preparation preserves existing initialize_fims output shape", {
  reset_julia_backend_state()
  testthat::local_mocked_bindings(
    initialize_julia_backend = function(...) FALSE,
    .package = "FIMS"
  )
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")
  julia_input <- attr(result, "julia_input")

  #' @description Test that Julia backend initialization still returns the standard two-element list.
  expect_named(result, c("parameters", "model"))
  #' @description Test that Julia backend initialization stores backend metadata as an attribute.
  expect_equal(attr(result, "backend"), "julia")
  #' @description Test that Julia backend initialization stores Julia input metadata as an attribute.
  expect_true(is.list(julia_input))
  #' @description Test that Julia backend initialization stores Julia input data and parameters.
  expect_named(julia_input, c("data", "parameters"))
  #' @description Test that Julia backend initialization now stores the Julia parameter payload directly in the returned list.
  expect_equal(result[["parameters"]], julia_input[["parameters"]])
  #' @description Test that Julia backend initialization no longer requires a TMB model object.
  expect_null(result[["model"]])
  #' @description Test that Julia backend input preserves the number of modeled years.
  expect_equal(julia_input[["data"]][["n_years"]], get_n_years(data))
  #' @description Test that Julia backend input preserves the modeled age bins.
  expect_equal(julia_input[["data"]][["ages"]], get_ages(data))
  #' @description Test that Julia backend input now includes weight-at-age and maturity matrices.
  expect_true(all(c("weights_at_age", "maturity_at_age") %in% names(julia_input[["data"]])))
  #' @description Test that Julia backend input includes serialized population and observation values.
  expect_true(all(c("proportion_female", "observed_catch") %in% names(julia_input[["data"]])))
  #' @description Test that Julia backend parameters are serialized to the named structure expected by the Julia objective scaffold.
  expect_true(all(c("log_Fmort", "log_M", "log_init_naa", "log_rzero", "logit_steep") %in% names(julia_input[["parameters"]])))
  #' @description Test that the Julia backend weight-at-age matrix has one row per modeled year and one column per age.
  expect_equal(dim(julia_input[["data"]][["weights_at_age"]]), c(get_n_years(data), get_n_ages(data)))
  #' @description Test that the Julia backend maturity-at-age matrix has one row per modeled year and one column per age.
  expect_equal(dim(julia_input[["data"]][["maturity_at_age"]]), c(get_n_years(data), get_n_ages(data)))
  #' @description Test that the serialized fishing mortality vector spans every year-age cell.
  expect_length(julia_input[["parameters"]][["log_Fmort"]], get_n_years(data) * get_n_ages(data))
  #' @description Test that the serialized natural mortality vector spans every year-age cell.
  expect_length(julia_input[["parameters"]][["log_M"]], get_n_years(data) * get_n_ages(data))
  #' @description Test that the serialized initial numbers-at-age preserve the original parameter order.
  expect_equal(
    julia_input[["parameters"]][["log_init_naa"]],
    parameters |>
      dplyr::filter(.data$module_name == "Population", .data$label == "log_init_naa") |>
      dplyr::pull(.data$value)
  )
  #' @description Test that the serialized fishing mortality preserves the original parameter order.
  expect_equal(
    julia_input[["parameters"]][["log_Fmort"]],
    parameters |>
      dplyr::filter(.data$module_name == "Fleet", .data$label == "log_Fmort") |>
      dplyr::pull(.data$value)
  )

  clear()
})

test_that("Julia backend initialize_fims skips TMB setup helpers", {
  reset_julia_backend_state()
  testthat::local_mocked_bindings(
    initialize_julia_backend = function(...) FALSE,
    CreateTMBModel = function(...) stop("CreateTMBModel should not be called"),
    get_fixed = function(...) stop("get_fixed should not be called"),
    get_random = function(...) stop("get_random should not be called"),
    .package = "FIMS"
  )
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)

  #' @description Test that initialize_fims() can prepare the Julia backend without calling the TMB setup helpers.
  expect_no_error(
    result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")
  )
  #' @description Test that the Julia backend still records its backend metadata when TMB setup is skipped.
  expect_equal(attr(result, "backend"), "julia")

  clear()
})

test_that("Julia backend serializer omits unavailable observed data entries", {
  reset_julia_backend_state()
  data <- data_big |>
    dplyr::filter(!.data$type %in% c("catch", "index", "age_comp")) |>
    FIMS::FIMSFrame()
  parameters <- FIMS::setup_default_parameters(data = data)
  julia_input <- FIMS:::prepare_julia_backend_input(parameters = parameters, data = data)

  #' @description Test that missing catch data are omitted from the Julia serializer output.
  expect_false("observed_catch" %in% names(julia_input[["data"]]))
  #' @description Test that missing index data are omitted from the Julia serializer output.
  expect_false("observed_index" %in% names(julia_input[["data"]]))
  #' @description Test that missing age-composition data are omitted from the Julia serializer output.
  expect_false("observed_age_comp" %in% names(julia_input[["data"]]))

  clear()
})

test_that("Julia backend serializer rejects unsupported multi-fleet observation inputs", {
  reset_julia_backend_state()
  make_multi_fleet_data <- function(data_type) {
    dplyr::bind_rows(
      data_big,
      data_big |>
        dplyr::filter(.data$type == .env$data_type, .data$fleet == "fleet1") |>
        dplyr::mutate(fleet = "fleet2")
    ) |>
      FIMS::FIMSFrame()
  }

  catch_data <- make_multi_fleet_data("catch")
  catch_parameters <- FIMS::setup_default_parameters(data = catch_data)
  #' @description Test that the experimental Julia serializer errors on unsupported multiple catch fleets.
  expect_error(
    FIMS:::prepare_julia_backend_input(parameters = catch_parameters, data = catch_data),
    regexp = "currently supports only one catch fleet"
  )

  index_data <- make_multi_fleet_data("index")
  index_parameters <- FIMS::setup_default_parameters(data = index_data)
  #' @description Test that the experimental Julia serializer errors on unsupported multiple index fleets.
  expect_error(
    FIMS:::prepare_julia_backend_input(parameters = index_parameters, data = index_data),
    regexp = "currently supports only one index fleet"
  )

  agecomp_data <- make_multi_fleet_data("age_comp")
  agecomp_parameters <- FIMS::setup_default_parameters(data = agecomp_data)
  #' @description Test that the experimental Julia serializer errors on unsupported multiple age-composition fleets.
  expect_error(
    FIMS:::prepare_julia_backend_input(parameters = agecomp_parameters, data = agecomp_data),
    regexp = "currently supports only one age-composition fleet"
  )

  clear()
})

test_that("Julia backend fit_fims returns a FIMSFit object through the Julia bridge", {
  reset_julia_backend_state()
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")
  julia_input <- attr(result, "julia_input")
  parameter_lengths <- purrr::map_int(julia_input[["parameters"]], length)
  flattened_parameter_count <- sum(parameter_lengths)
  mocked_report <- list(
   numbers_at_age = matrix(1, nrow = get_n_years(data), ncol = get_n_ages(data)),
   catch_numbers_at_age = matrix(0.1, nrow = get_n_years(data), ncol = get_n_ages(data)),
   biomass = rep(1, get_n_years(data)),
   spawning_biomass = rep(0.5, get_n_years(data)),
   expected_recruitment = rep(1, get_n_years(data)),
   catch_expected = rep(1, get_n_years(data)),
   index_expected = rep(0.5, get_n_years(data)),
   agecomp_expected = matrix(1 / get_n_ages(data), nrow = get_n_years(data), ncol = get_n_ages(data))
  )

  testthat::local_mocked_bindings(
   initialize_julia_backend = function(...) TRUE,
   assign_julia_backend_input = function(...) invisible(TRUE),
   fit_julia_backend_model = function(...) {
     list(
       estimates = julia_input[["parameters"]],
       standard_errors = purrr::imap(
         julia_input[["parameters"]],
         \(value, name) rep(0.1, length(value))
       ),
       gradient = rep(0, flattened_parameter_count),
       hessian = diag(flattened_parameter_count),
       nll = 12.5,
       convergence = TRUE,
       convergence_code = "SUCCESS",
       iterations = 4L,
       report = mocked_report
     )
   },
   .package = "FIMS"
  )

  fit <- FIMS::fit_fims(result, optimize = TRUE)

  #' @description Test that the Julia backend fit bridge now returns a FIMSFit object.
  expect_s4_class(fit, "FIMSFit")
  #' @description Test that the Julia backend fit bridge preserves backend metadata in the fit input.
  expect_equal(attr(FIMS::get_input(fit), "backend"), "julia")
  #' @description Test that the Julia backend fit bridge records an optimizer result.
  expect_equal(FIMS::get_opt(fit)[["convergence"]], 0L)
  #' @description Test that the Julia backend fit bridge exposes the Julia report jnll through get_report().
  expect_equal(FIMS::get_report(fit)[["jnll"]], 12.5)
  #' @description Test that Julia backend fits produce estimate rows for the serialized catch data stream.
  expect_true("catch_expected" %in% FIMS::get_estimates(fit)[["label"]])
  #' @description Test that Julia backend fits support backend-neutral glance summaries.
  expect_equal(generics::glance(fit)[["marginal_nll"]], 12.5)

  clear()
})

test_that("Julia backend fit_fims errors cleanly when Julia cannot initialize", {
  reset_julia_backend_state()
  testthat::local_mocked_bindings(
   initialize_julia_backend = function(...) FALSE,
   .package = "FIMS"
  )
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that Julia-backed fit_fims fails with a Julia initialization error when the runtime is unavailable.
  expect_error(
   FIMS::fit_fims(result, optimize = TRUE),
   regexp = "Julia backend initialization failed"
  )
})

test_that("Julia backend initialization stays shaped correctly when Julia startup is disabled", {
  reset_julia_backend_state()
  withr::local_options(list(FIMS.disable_julia = TRUE))
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that disabling Julia startup still preserves the standard initialize_fims output shape.
  expect_named(result, c("parameters", "model"))
  #' @description Test that disabling Julia startup still preserves Julia input metadata.
  expect_true(is.list(attr(result, "julia_input")))

  clear()
})

test_that("Julia backend initialization assigns prepared input when Julia startup succeeds", {
  reset_julia_backend_state()
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  assigned <- FALSE
  assigned_input <- NULL

  testthat::local_mocked_bindings(
    initialize_julia_backend = function(...) TRUE,
    assign_julia_backend_input = function(x) {
      assigned <<- TRUE
      assigned_input <<- x
      invisible(TRUE)
    },
    .package = "FIMS"
  )

  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that the Julia assignment branch is reached when Julia startup succeeds.
  expect_true(assigned)
  #' @description Test that the Julia assignment branch receives the same serialized input attached to the returned object.
  expect_equal(assigned_input, attr(result, "julia_input"))
  #' @description Test that the Julia assignment branch preserves the serialized data payload structure.
  expect_named(assigned_input[["data"]], names(attr(result, "julia_input")[["data"]]))
  #' @description Test that the Julia assignment branch preserves the serialized parameter payload structure.
  expect_named(assigned_input[["parameters"]], names(attr(result, "julia_input")[["parameters"]]))
  #' @description Test that the Julia backend success branch still preserves backend metadata.
  expect_equal(attr(result, "backend"), "julia")

  clear()
})

test_that("assign_julia_backend_input calls the Julia-side backend setter", {
  payload <- list(
    data = list(n_years = 1L),
    parameters = list(log_rzero = 0)
  )
  called <- list(fun = NULL, data = NULL, parameters = NULL)

  testthat::local_mocked_bindings(
    julia_call = function(fun, data, parameters) {
      called$fun <<- fun
      called$data <<- data
      called$parameters <<- parameters
      invisible(TRUE)
    },
    .package = "JuliaCall"
  )

  FIMS:::assign_julia_backend_input(payload)

  #' @description Test that assign_julia_backend_input targets the Julia-side backend setter.
  expect_equal(called$fun, "FIMSBackend.set_backend_input!")
  #' @description Test that assign_julia_backend_input forwards the data payload unchanged.
  expect_equal(called$data, payload[["data"]])
  #' @description Test that assign_julia_backend_input forwards the parameter payload unchanged.
  expect_equal(called$parameters, payload[["parameters"]])
})

test_that("Julia backend initialization skips assignment when Julia startup does not complete", {
  reset_julia_backend_state()
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  assigned <- FALSE

  testthat::local_mocked_bindings(
    initialize_julia_backend = function(...) FALSE,
    assign_julia_backend_input = function(x) {
      assigned <<- TRUE
      invisible(x)
    },
    .package = "FIMS"
  )

  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that the Julia assignment branch is skipped when initialization does not complete.
  expect_false(assigned)
  #' @description Test that the Julia backend still records the backend metadata when initialization is skipped.
  expect_equal(attr(result, "backend"), "julia")

  clear()
})
