# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().

test_that("Julia backend package scaffolding exists", {
  backend_root <- normalizePath(
    testthat::test_path("..", "..", "inst", "julia", "FIMSBackend"),
    winslash = "/",
    mustWork = TRUE
  )

  #' @description Test that the Julia backend Project.toml exists.
  expect_true(file.exists(file.path(backend_root, "Project.toml")))
  #' @description Test that the Julia backend top-level module exists.
  expect_true(file.exists(file.path(backend_root, "src", "FIMSBackend.jl")))
  #' @description Test that the Julia backend selectivity module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "selectivity.jl")))
  #' @description Test that the Julia backend recruitment module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "recruitment.jl")))
  #' @description Test that the Julia backend population module exists.
  expect_true(file.exists(file.path(backend_root, "src", "modules", "population.jl")))
})

test_that("Julia backend helpers return package paths", {
  backend_path <- FIMS:::julia_backend_package_path()
  module_path <- FIMS:::julia_backend_module_path()

  #' @description Test that the Julia backend package path is a character scalar.
  expect_type(backend_path, "character")
  #' @description Test that the Julia backend module path is a character scalar.
  expect_type(module_path, "character")
})

test_that("Julia backend input preparation preserves existing initialize_fims output shape", {
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")
  julia_input <- attr(result, "julia_input")

  #' @description Test that Julia backend initialization still returns the standard two-element list.
  expect_named(result, c("parameters", "model"))
  #' @description Test that Julia backend initialization stores backend metadata as an attribute.
  expect_equal(attr(result, "backend"), "julia")
  #' @description Test that Julia backend initialization stores Julia input metadata as an attribute.
  expect_true(is.list(julia_input))
  #' @description Test that Julia backend initialization stores Julia input data and parameters.
  expect_named(julia_input, c("data", "parameters"))
  #' @description Test that Julia backend input preserves the parameter row count.
  expect_equal(nrow(julia_input[["parameters"]]), nrow(parameters))
  #' @description Test that Julia backend input preserves the number of modeled years.
  expect_equal(julia_input[["data"]][["n_years"]], get_n_years(data))
  #' @description Test that Julia backend input preserves the modeled age bins.
  expect_equal(julia_input[["data"]][["ages"]], get_ages(data))

  clear()
})

test_that("Julia backend input errors in fit_fims until the fit bridge is complete", {
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that Julia backend input triggers the current explicit fit_fims guard.
  expect_error(
    FIMS::fit_fims(result, optimize = TRUE),
    regexp = "not yet fully wired into"
  )

  clear()
})

test_that("Julia backend initialization stays shaped correctly when Julia startup is disabled", {
  withr::local_options(list(FIMS.disable_julia = TRUE))
  data <- FIMS::FIMSFrame(data_big)
  parameters <- FIMS::setup_default_parameters(data = data)
  result <- FIMS::initialize_fims(parameters = parameters, data = data, backend = "julia")

  #' @description Test that disabling Julia startup still preserves the standard initialize_fims output shape.
  expect_named(result, c("parameters", "model"))
  #' @description Test that disabling Julia startup still preserves Julia input metadata.
  expect_true(is.list(attr(result, "julia_input")))

  clear()
})
